# Generated by Django 2.2 on 2020-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20200228_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='hero_headshots/'),
        ),
    ]
