# Generated by Django 2.2 on 2020-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_hero_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='added_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
