# Generated by Django 2.2 on 2020-02-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_villain_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villain',
            name='added_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
