# Generated by Django 2.2 on 2020-02-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20200228_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='headshot',
        ),
    ]
