# Generated by Django 2.2 on 2020-02-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_heroacquaintance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'constraints': [],
                'proxy': True,
            },
            bases=('entities.hero',),
        ),
    ]
