# Generated by Django 2.2 on 2020-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0013_hero_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'entities_entity',
            },
        ),
    ]
