# Generated by Django 2.2 on 2020-02-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_allentity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allentity',
            table='entity',
        ),
    ]
