# Generated by Django 2.2 on 2020-02-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20200228_1133'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allentity',
            table='entities_entity',
        ),
    ]
