# Generated by Django 2.2 on 2020-02-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_auto_20200228_1136'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allentity',
            table='entity',
        ),
    ]
