# Generated by Django 2.2 on 2020-02-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0017_auto_20200228_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllEntity',
        ),
    ]
