# Generated by Django 2.2 on 2020-03-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0019_allentity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allentity',
            table='oentity',
        ),
    ]
