# Generated by Django 2.2 on 2020-03-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0020_auto_20200303_1021'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allentity',
            table='entity',
        ),
    ]
