# Generated by Django 2.2 on 2020-03-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0022_flexcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexCategory',
        ),
    ]
